@echo off
echo Compilando con Maven...
call mvn clean package
echo Maven terminado. Bajando contenedores...
call docker-compose down
echo Subiendo contenedores...
call docker-compose up --build
pause
